### ISSUE TITLE
why not use latest version of django ?

### ISSUE THREAD

**Issue by cyrfer** [potatolondon/djangae-scaffold#104]
This script shows pip should not download django version 1.10 or greater. Why?

https://github.com/potatolondon/djangae-scaffold/blob/master/requirements/prod.txt#L2

**Comment by moggers87** [comment]
See https://github.com/potatolondon/djangae/issues/749

You can install Djangae from git master if you need Django 1.10 support :)

**Comment by adamalton** [comment]
There's also the consideration that Django 1.8 has long term support,
whereas 1.9 and 1.10 don't.

**Comment by cyrfer** [comment]
Thank you for the explanation. I will close this.

@adamalton - I realize this sounds idealist, but I assume the latest version of a project works with the latest version of a dependency. It makes it much easier to get started when this is true.
