### ISSUE TITLE
Add a checksecure check for CSP headers

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae-scaffold#22]
We should add a check which `checksecure` will run to ensure that a project has got a sensible Content Security Policy setup and is outputting the headers correctly.

**Comment by adamalton** [comment]
This should also ensure that CSP is **not** in `report-only` mode.

**Comment by adamalton** [comment]
See our existing custom check as a starting point: https://github.com/potatolondon/djangae-scaffold/blob/master/scaffold/settings.py#L71-L76

We should probably move them into a separate file though.

**Comment by Kazade** [comment]
Fixed
