### ISSUE TITLE
Add a better default CSP set up

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae-scaffold#31]
Having `'self'` as the `default-src` for CSP is secure, but it might just provoke people into "my site doesn't work, I'll just turn off this CSP thing".

So we should consider having a slightly better default set up, which will not only allow common things (e.g. Google Fonts), but will also be a good example/starting point which people can work from (rather than having to go and read the `django-csp` documentation to find out what the available settings are.

Possibly it could just be added in a commented block, as an example set up.

Most of the things in [gae-secure-scaffold-python](https://github.com/google/gae-secure-scaffold-python/blob/master/src/main.py#L97-L111) are probably generally useful.

**Comment by Kazade** [comment]
Fixed!
