### ISSUE TITLE
Duplicate X-Frame-Options middleware?

### ISSUE THREAD

**Issue by pames** [potatolondon/djangae-scaffold#36]
Djangae-scaffold incorporates both:
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
and
    'djangosecure.middleware.SecurityMiddleware',

Are both of these necessary?

http://django-secure.readthedocs.org/en/v0.1.2/middleware.html implies that it's not.

**Comment by jasoncartwright** [comment]
Good call. Thanks @pames
