### ISSUE TITLE
Recommendation for installing PIL

### ISSUE THREAD

**Issue by rchrd2** [potatolondon/djangae-scaffold#41]
How would one install PIL to be used for development?

# requirements.txt
```
git+https://github.com/potatolondon/djangae.git#egg=djangae
django>=1.7,<1.8
django-secure
django-csp
git+https://github.com/adamalton/django-csp-reports.git#egg=cspreports
django-session-csrf
nose
six

# ---
django-stdimage
django-admin-sortable2
pillow
```

# install deps
```
sudo ./install_deps
```

I get the following error when uploading an image.
```
Neither Pillow nor PIL could be imported: No module named Image
```

**Comment by adamalton** [comment]
It depends which platform you're on.  I'm not going to be able to offer any
better advice than what you can find via Google though, so just search for
"Install PIL on Linux/OS X/Windows/whatever" and follow the latest wisdom.

**Comment by rchrd2** [comment]
I see. The thing is, I've successfully installed it for many other projects. I was curious if djangae does any sandboxing of libraries that might be blocking the inclusion of PIL?

For another GAE project I just installed PIL globally and it worked. That's not working with djangae. Thoughts?

**Comment by rchrd2** [comment]
It also appears that I can import it from `./manage.py shell`

```
>./manage.py shell
>>> from PIL import Image
>>> 
```

But it still can't find it in `runserver`.

**Comment by rchrd2** [comment]
I figured it out! It was some GAE black magic. I had to add the following to my app.yaml, and it magically worked.

```
libraries:
- name: PIL
  version: "latest"
```
