### ISSUE TITLE
How to use @login_required with Gauth?

### ISSUE THREAD

**Issue by morninj** [potatolondon/djangae-scaffold#47]
When I try to add the `@login_required` decorator to a view, this exception happens:

    NoReverseMatch: Reverse for 'djangae_login_redirect' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: [] 

How do I enable users to log in with their Google accounts?

**Comment by chargrizzle** [comment]
Hey morninj,

Do you have djangae.contrib.gauth.... in your installed apps? 

http://djangae.readthedocs.org/en/latest/gauth/index.html?highlight=gauth

**Comment by morninj** [comment]
Yes—this is enabled by default in `settings.py` in `djangae-scaffold`. I figured out that I can login by navigating to `https://[myapp]/admin/`, which redirects to a Google authentication screen. Once I log in from there, `@login_required` works. But if I haven't logged in from `/admin/`, then `@login_required` still throws `NoReverseMatch`. There also doesn't appear to be a way to log out.

**Comment by adamalton** [comment]
I think you just need to `include('djangae.contrib.gauth.urls')` in your root URL conf file, and that should sort it.

That appears to be missing from the docs.  I'll add it.

**Comment by morninj** [comment]
That works—thanks!
