### ISSUE TITLE
Make a Django project template out of djangae-scaffold

### ISSUE THREAD

**Issue by olasitarska** [potatolondon/djangae-scaffold#49]
This was a conclusion from #26. [Relevant docs](https://docs.djangoproject.com/en/1.7/ref/django-admin/#startproject-projectname-destination).

**Comment by luzfcb** [comment]
consider using [cookiecutter](https://github.com/audreyr/cookiecutter) because it is more flexible.

some good examples of what can be accomplished with cookiecutter:

https://github.com/ionelmc/cookiecutter-pylibrary

https://github.com/pydanny/cookiecutter-django
