### ISSUE TITLE
rename_scaffold_app syntax error on Linux

### ISSUE THREAD

**Issue by slumtrimpet** [potatolondon/djangae-scaffold#51]
Had to update the find/sed call to the following on Linux:

```
find . -path ./sitepackages -prune -o \( -name '*.py' -o -name 'app.yaml' \) -print -exec sed -i "s/scaffold/$1/g" {} +;
```

**Comment by adamalton** [comment]
Would you be so kind as to make a pull request for this?  It probably needs an `if` statement to do it differently on Linux (unless the Linux-friendly syntax also works on OS X and Windows).

**Comment by slumtrimpet** [comment]
https://github.com/potatolondon/djangae-scaffold/pull/52
