### ISSUE TITLE
[Help] djangae without google authentication?!

### ISSUE THREAD

**Issue by andretietz** [potatolondon/djangae-scaffold#62]
I am pretty new to django (and app engine too) and I'ld like to as you for help.

I have my django project running already on openshift but I want to try it on gae too, but with a username/password login (as it is django default) third party logins, I want to add with allauth (or smth similar). What do I have to change in (renamed) scaffold project?

**Comment by moggers87** [comment]
I'd suggest heading over to the [mailing list](https://groups.google.com/forum/#!forum/djangae-users) or use [gitter chat](https://gitter.im/potatolondon/djangae). More users there who could help :)
