### ISSUE TITLE
Migrate from django-secure to the same features in Django

### ISSUE THREAD

**Issue by olasitarska** [potatolondon/djangae-scaffold#76]
As Djangae is now supporting 1.8 and 1.9 only, we can remove django-secure and add relevant checks that are now in Django. Django-secure is not supporting 1.9, so djangae-scaffold breaks when installed with Django 1.9 :(

**Comment by MihailRussu** [comment]
Any updates on this? Would love to try out djangae and sound like djangae-scaffold is a good start but it doesn't seem to work with latest Django due to this issue.

**Comment by niranjan92** [comment]
+1

**Comment by zacharytamas** [comment]
Any progress on merging this PR? I'm facing this problem too.

**Comment by olasitarska** [comment]
This has been fixed now.
