### ISSUE TITLE
python manage.py test with database

### ISSUE THREAD

**Issue by briva** [potatolondon/djangae-scaffold#93]
Hello :)

I'm currently trying to setup djangae and I got some problem with testing.

I setup mysql, manage.py migrate working well. But manage test give that :

> django.db.utils.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'list NULL)' at line 1")

**Comment by moggers87** [comment]
Did you forget to change `'djangae.contrib.gauth.datastore` to `djangae.contrib.gauth.sql` in your settings.py?

**Comment by briva** [comment]
@moggers87  Yes I forgot, I did. 

But now I get another issue : 

python manage.py migrate ->

> django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`be_database`.`auth_permission`, CONSTRAINT `auth_permissi_content_type_id_2f476e4b_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`))')

**Comment by adamalton** [comment]
Ah, that's probably the content types optimisation patch, which if you're using SQL isn't really needed anyway.

Try removing `djangae.contrib.contenttypes` from `INSTALLED_APPS`.

**Comment by briva** [comment]
I cant :/

> django.core.exceptions.ImproperlyConfigured: If you're using django.contrib.contenttypes, then you need to add djangae.contrib.contenttypes to INSTALLED_APPS after django.contrib.contenttypes.
Brivaels-M

**Comment by asendecka** [comment]
@briva add `djangae.contrib.contenttypes` after `django.contrib.contenttypes` in your `INSTALLED_APPS`

**Comment by briva** [comment]
@asendecka I did but still this bug :

> django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`owls_be`.`auth_permission`, CONSTRAINT `auth_permissi_content_type_id_2f476e4b_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`))')

**Comment by adamalton** [comment]
Do you have the traceback for that error?  I.e. can you see which line in djangae/apps.py it's being raised from?

**Comment by briva** [comment]
This one :

> Traceback (most recent call last):
>   File "./manage.py", line 13, in <module>
>     execute_from_command_line(sys.argv)
>   File "lib/djangae/core/management/__init__.py", line 65, in execute_from_command_line
>     return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
>   File "lib/djangae/core/management/__init__.py", line 45, in _execute_from_command_line
>     return django_management.execute_from_command_line(argv)
>   File "lib/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "lib/django/core/management/__init__.py", line 345, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "lib/django/core/management/base.py", line 348, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "lib/django/core/management/base.py", line 399, in execute
>     output = self.handle(*args, **options)
>   File "lib/django/core/management/commands/migrate.py", line 204, in handle
>     emit_post_migrate_signal(self.verbosity, self.interactive, connection.alias)
>   File "lib/django/core/management/sql.py", line 50, in emit_post_migrate_signal
>     using=db)
>   File "lib/django/dispatch/dispatcher.py", line 192, in send
>     response = receiver(signal=self, sender=sender, **named)
>   File "lib/django/contrib/auth/management/__init__.py", line 126, in create_permissions
>     Permission.objects.using(using).bulk_create(perms)
>   File "lib/django/db/models/query.py", line 450, in bulk_create
>     self._batched_insert(objs_without_pk, fields, batch_size)
>   File "lib/django/db/models/query.py", line 1056, in _batched_insert
>     using=self.db)
>   File "lib/django/db/models/manager.py", line 122, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "lib/django/db/models/query.py", line 1039, in _insert
>     return query.get_compiler(using=using).execute_sql(return_id)
>   File "lib/django/db/models/sql/compiler.py", line 1060, in execute_sql
>     cursor.execute(sql, params)
>   File "lib/django/db/backends/utils.py", line 79, in execute
>     return super(CursorDebugWrapper, self).execute(sql, params)
>   File "lib/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "lib/django/db/utils.py", line 95, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "lib/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "lib/django/db/backends/mysql/base.py", line 112, in execute
>     return self.cursor.execute(query, args)
>   File "lib/MySQLdb/cursors.py", line 205, in execute
>     self.errorhandler(self, exc, value)
>   File "lib/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorclass, errorvalue
> django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`owls_be`.`auth_permission`, CONSTRAINT `auth_permissi_content_type_id_2f476e4b_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`))')

**Comment by adamalton** [comment]
Ah, no, the other one!

**Comment by briva** [comment]
> INFO     2016-06-21 15:38:44,623 blobstore_service.py:73] Starting blobstore service on localhost:8080
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "lib/djangae/core/management/__init__.py", line 65, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "lib/djangae/core/management/__init__.py", line 45, in _execute_from_command_line
    return django_management.execute_from_command_line(argv)
  File "lib/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "lib/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "lib/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "lib/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "lib/djangae/apps.py", line 26, in ready
    raise contenttype_configuration_error
django.core.exceptions.ImproperlyConfigured: If you're using django.contrib.contenttypes, then you need to add djangae.contrib.contenttypes to INSTALLED_APPS after django.contrib.contenttypes.

**Comment by briva** [comment]
I just comment this block 

`contenttype_configuration_error = ImproperlyConfigured(
            "If you're using django.contrib.contenttypes, then you need "
            "to add djangae.contrib.contenttypes to INSTALLED_APPS after "
            "django.contrib.contenttypes."
        )
        if 'django.contrib.contenttypes' in settings.INSTALLED_APPS:
            if not 'djangae.contrib.contenttypes' in settings.INSTALLED_APPS:
                # Raise error if User is using Django CT, but not Djangae
                raise contenttype_configuration_error
            else:
                if settings.INSTALLED_APPS.index('django.contrib.contenttypes') > \
                        settings.INSTALLED_APPS.index('djangae.contrib.contenttypes'):
                    # Raise error if User is using both Django and Djangae CT, but
                    # Django CT comes after Djangae CT
                    raise contenttype_configuration_error`

fix the pb

**Comment by olasitarska** [comment]
If you're using Djangae with SQL, `djangae.contrib.contenttypes` should not be in `INSTALLED_APPS`. If the error you just pasted here occurs, you need to install newest version of Djangae from Github -- the currently released one to PyPI (0.9.5) has this error.

**Comment by briva** [comment]
Yes you're right @olasitarska Thank you ! 👍

**Comment by olasitarska** [comment]
:+1: Good luck!
