### ISSUE TITLE
Error in csp/utils.py?

### ISSUE THREAD

**Issue by WeaverStever** [potatolondon/djangae-scaffold#95]
Is this me? Or something else?  
Platform is Ubuntu 14.04 desktop
Thanks!

TypeError at /
sequence item 0: expected string, __proxy__ found
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Django Version:	1.9.8
Exception Type:	TypeError
Exception Value:	
sequence item 0: expected string, __proxy__ found
Exception Location:	/home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/sitepackages/csp/utils.py in build_policy, line 58
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/home/username/Documents/Workspace/djangae-scaffold/ParkingBeater',
 '/home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/sitepackages/djangae/lib',
 '/home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/sitepackages',
 '/home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/sitepackages/google_appengine',
 '/home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/sitepackages/google_appengine',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/lib-dynload',
 '/home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/sitepackages/google_appengine/lib/protorpc-1.0',
 '/home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/sitepackages/google_appengine/lib/webapp2-2.3',
 '/home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/sitepackages/google_appengine/lib/webob-1.1.1',
 '/home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/sitepackages/google_appengine/lib/yaml-3.10']
Server time:	Sun, 24 Jul 2016 02:05:57 +0000

**Comment by mattdoughty** [comment]
This is a bug with django-csp, see here: https://github.com/mozilla/django-csp/issues/67

It's fixed but hasn't been pushed to PyPI yet, so you could update the requirements file to pull directly from GitHub

**Comment by WeaverStever** [comment]
Thanks for your quick response. Still getting the same error, but a little more info.

I added: git+https://github.com/mozilla/django-csp.git
on the third line of settings.txt

Running the setup instructions (readme.md) again. Partial output from: $ python manage.py check --deploy --settings=parkingbeater.settings_live

Errors?
1. Could not find .egg-info directory in install record for djangae...
2.  Could not find .egg-info directory in install record for cspreports...

Downloading/unpacking django-session-csrf (from -r /home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/requirements.txt (line 6))
  Downloading django_session_csrf-0.6-py2-none-any.whl
Downloading/unpacking nose (from -r /home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/requirements.txt (line 7))
  Downloading nose-1.3.7-py2-none-any.whl (154kB): 154kB downloaded
Downloading/unpacking six (from -r /home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/requirements.txt (line 8))
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: djangae, django, django-csp, cspreports, django-session-csrf, nose, six
  Running setup.py install for djangae
    
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
  Could not find .egg-info directory in install record for djangae from git+https://github.com/potatolondon/djangae.git (from -r /home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/requirements.txt (line 1))
  Running setup.py install for cspreports
    
  Could not find .egg-info directory in install record for cspreports from git+https://github.com/adamalton/django-csp-reports.git (from -r /home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/requirements.txt (line 5))
Successfully installed djangae django django-csp cspreports django-session-csrf nose six
Cleaning up...
username@username-MS-7596:~/Documents/Workspace/djangae-scaffold/ParkingBeater$ python manage.py check --deploy --settings=parkingbeater.settings_live
INFO     2016-07-23 20:44:09,165 blobstore_service.py:73] Starting blobstore service on localhost:8080
WARNING  2016-07-24 03:44:09,363 __init__.py:107] /home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/sitepackages/cspreports/urls.py:7: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got report_csp). Pass the callable instead.
  url(r'^report/$', 'report_csp', name='report_csp'),

WARNING  2016-07-24 03:44:09,363 __init__.py:84] /home/username/Documents/Workspace/djangae-scaffold/ParkingBeater/sitepackages/cspreports/urls.py:7: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^report/$', 'report_csp', name='report_csp'),

System check identified no issues (1 silenced).

**Comment by nealedj** [comment]
I think it looks like you still don't have the updated csp version.

It says that the error is being thrown on line 58 of `utils.py`. That should be on line 60 with the updated library.

**Comment by WeaverStever** [comment]
Okay, I got it.  The pull request wasn't working for me? I downloaded the latest and manually pasted the csp content (https://github.com/mozilla/django-csp.git) into my project's csp directory.

Thanks!
